TwitchEmotes_Moosebrother_Emoticons = {
    ["AAAA"] = "AAAA",
    ["HotBois"] = "HotBois",
    ["mbroA"] = "mbroA",
    ["mbroAFK"] = "mbroAFK",
    ["mbroBloompa"] = "mbroBloompa",
    ["mbroBuffer"] = "mbroBuffer",
    ["mbroChomp"] = "mbroChomp",
    ["mbroClassic"] = "mbroClassic",
    ["mbroCozy"] = "mbroCozy",
    ["mbroCringe"] = "mbroCringe",
    ["mbroCult"] = "mbroCult",
    ["mbroD"] = "mbroD",
    ["mbroDerp"] = "mbroDerp",
    ["mbroDumpy"] = "mbroDumpy",
    ["mbroE"] = "mbroE",
    ["mbroEeBey"] = "mbroEeBey",
    ["mbroEZ"] = "mbroEZ",
    ["mbroFat"] = "mbroFat",
    ["mbroFlower"] = "mbroFlower",
    ["mbroGun"] = "mbroGun",
    ["mbroH"] = "mbroH",
    ["mbroHey"] = "mbroHey",
    ["mbroHiccup"] = "mbroHiccup",
    ["mbroHmm"] = "mbroHmm",
    ["mbroHS"] = "mbroHS",
    ["mbroHype"] = "mbroHype",
    ["mbroJAM"] = "mbroJAM",
    ["mbroKaren"] = "mbroKaren",
    ["mbroKnife"] = "mbroKnife",
    ["mbroL"] = "mbroL",
    ["mbroLewd"] = "mbroLewd",
    ["mbroLUL"] = "mbroLUL",
    ["mbroLurk"] = "mbroLurk",
    ["MegaWorry"] = "MegaWorry",
    ["mbroNotepad"] = "mbroNotepad",
    ["mbroPain"] = "mbroPain",
    ["mbroPopcorn"] = "mbroPopcorn",
    ["mbroPrayge"] = "mbroPrayge",
    ["mbroPride"] = "mbroPride",
    ["mbroR"] = "mbroR",
    ["mbroRare"] = "mbroRare",
    ["mbroRIP"] = "mbroRIP",
    ["mbroRun"] = "mbroRun",
    ["mbroS"] = "mbroS",
    ["mbroS1"] = "mbroS1",
    ["mbroS2"] = "mbroS2",
    ["mbroS3"] = "mbroS3",
    ["mbroS4"] = "mbroS4",
    ["mbroSleep"] = "mbroSleep",
    ["mbroSpoon"] = "mbroSpoon",
    ["mbroStare"] = "mbroStare",
    ["mbroStir"] = "mbroStir",
    ["mbroSuffer"] = "mbroSuffer",
    ["mbroSUSGE"] = "mbroSUSGE",
    ["mbroTired"] = "mbroTired",
    ["mbroV"] = "mbroV",
    ["mbroW"] = "mbroW",
    ["mbroWake"] = "mbroWake",
    ["mbroWall"] = "mbroWall",
    ["mbroWave"] = "mbroWave",
    ["mbroWICKED"] = "mbroWICKED",
    ["mbroWiggle"] = "mbroWiggle",
    ["mbroWOW"] = "mbroWOW",
    ["mbroWWICKED"] = "mbroWWICKED",
    ["POGWAN"] = "POGWAN",
    ["poggSpin"] = "poggSpin",
    ["WAGWANMB"] = "WAGWANMB",
    ["mbroWaiting"] = "mbroWaiting",
    ["Zara"] = "Zara",
    ["zara"] = "zara",
}

TwitchEmotes_Moosebrother_Emoticons_Pack = {
    ["AAAA"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\AAAA.tga",
    ["HotBois"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\HotBois.tga",
    ["mbroA"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroA.tga:28:28",
    ["mbroAFK"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroAFK.tga:28:28",
    ["mbroBloompa"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroBloompa.tga:28:28",
    ["mbroBuffer"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroBuffer.tga:28:28",
    ["mbroChomp"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroChomp.tga",
    ["mbroClassic"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroClassic.tga:28:28",
    ["mbroCozy"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroCozy.tga:28:28",
    ["mbroCringe"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroCringe.tga:28:28",
    ["mbroCult"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroCult.tga:28:28",
    ["mbroD"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroD.tga:28:28",
    ["mbroDerp"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroDerp.tga:28:28",
    ["mbroDumpy"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroDumpy.tga:28:28",
    ["mbroE"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroE.tga:28:28",
    ["mbroEeBey"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroEeBey.tga:28:28",
    ["mbroEZ"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroEZ.tga:28:28",
    ["mbroFat"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroFat.tga:28:28",
    ["mbroFlower"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroFlower.tga:28:28",
    ["mbroGun"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroGun.tga:28:28",
    ["mbroH"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroH.tga:28:28",
    ["mbroHey"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroHey.tga:28:28",
    ["mbroHiccup"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroHiccup.tga:28:28",
    ["mbroHmm"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroHmm.tga:28:28",
    ["mbroHS"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroHS.tga:28:28",
    ["mbroHype"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroHype.tga:28:28",
    ["mbroJAM"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroJAM.tga:28:28",
    ["mbroKaren"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroKaren.tga:28:28",
    ["mbroKnife"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroKnife.tga:28:28",
    ["mbroL"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroL.tga:28:28",
    ["mbroLewd"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroLewd.tga:28:28",
    ["mbroLUL"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroLUL.tga:28:28",
    ["mbroLurk"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroLurk.tga:28:28",
    ["MegaWorry"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\MegaWorry.tga:28:28",
    ["mbroNotepad"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroNotepad.tga:28:28",
    ["mbroPain"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroPain.tga:28:28",
    ["mbroPopcorn"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroPopcorn.tga:28:28",
    ["mbroPrayge"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroPrayge.tga:28:28",
    ["mbroPride"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroPride.tga:28:28",
    ["mbroR"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroR.tga:28:28",
    ["mbroRare"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroRare.tga:28:28",
    ["mbroRIP"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroRIP.tga:28:28",
    ["mbroRun"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroRun.tga",
    ["mbroS"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroS.tga:28:28",
    ["mbroS1"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroS1.tga:28:28",
    ["mbroS2"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroS2.tga:28:28",
    ["mbroS3"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroS3.tga:28:28",
    ["mbroS4"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroS4.tga:28:28",
    ["mbroSleep"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroSleep.tga:28:28",
    ["mbroSpoon"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroSpoon.tga:28:28",
    ["mbroStare"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroStare.tga:28:28",
    ["mbroStir"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroStir.tga:28:28",
    ["mbroSuffer"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroSuffer.tga:28:28",
    ["mbroSUSGE"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroSUSGE.tga:28:28",
    ["mbroTired"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroTired.tga:28:28",
    ["mbroV"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroV.tga:28:28",
    ["mbroW"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroW.tga:28:28",
    ["mbroWake"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroWake.tga:28:28",
    ["mbroWall"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroWall.tga:28:28",
    ["mbroWave"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroWave.tga:28:28",
    ["mbroWICKED"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroWICKED.tga:28:28",
    ["mbroWiggle"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroWiggle.tga:28:28",
    ["mbroWOW"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroWOW.tga:28:28",
    ["mbroWWICKED"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroWWICKED.tga:28:28",
    ["POGWAN"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\POGWAN.tga:28:28",
    ["poggSpin"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\poggSpin.tga",
    ["WAGWANMB"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\WAGWANMB.tga:28:28",
    ["mbroWaiting"] = "Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroWaiting.tga:28:28",
    ["Zara"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Custom\\meow.tga",
    ["zara"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Custom\\meow.tga",
}

--[[
    Animation Metadata Table
    
    For each animated emote, define:
    - nFrames: Number of frames in the sprite sheet
    - frameWidth: Width of each frame (always 32)
    - frameHeight: Height of each frame (always 32)
    - imageWidth: Total image width (always 32)
    - imageHeight: Total image height (must be power of 2: 64, 128, 256, 512, 1024, 2048)
    - framerate: Playback speed in frames per second
    - pingpong: (optional) If true, animation plays forward then backward
    
    See Animator.lua for detailed instructions on creating animated emotes.
]]
TwitchEmotes_Moosebrother_Animation_Metadata = {
    ["Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\AAAA.tga"] = {nFrames = 7, frameWidth = 32, frameHeight = 32, imageWidth = 32, imageHeight = 256, framerate = 30},
    ["Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\HotBois.tga"] = {nFrames = 19, frameWidth = 32, frameHeight = 32, imageWidth = 32, imageHeight = 1024, framerate = 15},
    ["Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroChomp.tga"] = {nFrames = 6, frameWidth = 32, frameHeight = 32, imageWidth = 32, imageHeight = 256, framerate = 15},
    ["Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\mbroRun.tga"] = {nFrames = 15, frameWidth = 32, frameHeight = 32, imageWidth = 32, imageHeight = 512, framerate = 15},
    ["Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\poggSpin.tga"] = {nFrames = 6, frameWidth = 32, frameHeight = 32, imageWidth = 32, imageHeight = 256, framerate = 15},
    -- Example:
    -- ["Interface\\AddOns\\TwitchEmotes_Moosebrother\\emotes\\example.tga"] = {
    --     nFrames = 24,
    --     frameWidth = 32,
    --     frameHeight = 32,
    --     imageWidth = 32,
    --     imageHeight = 1024,
    --     framerate = 15,
    -- },
}